image: registry.gitlab.com/sum01/vcash-calculator:latest

stages:
  - test
  - deploy

test:eslint:
  stage: test
  script:
    - eslint -c "$(pwd)/.eslintrc.json" public/main.js

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
  only:
    - master
